#!/usr/bin/env python3
"""Translate Chinese strings in HTML files to English"""
import re

TRANSLATIONS = {
    # --- MANUAL FULL SENTENCE TRANSLATIONS (Priority) ---
    # Import Modal
    "优先使用AT导入（推荐）": "Prefer AT Import (Recommended)",
    "离线导入（不更新账号状态）": "Offline Import (Does not update account status)",
    "优先使用ST导入": "Prefer ST Import",
    "优先使用RT导入": "Prefer RT Import",
    "使用AT更新账号状态（订阅信息、Sora2次数等）": "Use AT to update account status (subscription, Sora2 limits, etc.)",
    "离线导入，不更新账号状态，动态字段显示为-": "Offline import: No status update, dynamic fields shown as '-'",
    "自动将ST转换为AT，然后更新账号状态": "Auto convert ST -> AT, then update account status",
    "自动将RT转换为AT（并刷新RT），然后更新账号状态": "Auto convert RT -> AT (refreshes RT), then update status",
    "直接插入数据库，快速导入不调用API，账号信息需要单独获取 -": "Insert directly into DB. Quick import (no API calls). Account info must be fetched separately.",
    "适用于只有ST没有AT，自动转换为AT": "For when you have ST but no AT. Auto converts to AT.",
    "适用于只有RT没有AT，自动转换为AT": "For when you have RT but no AT. Auto converts to AT.",
    "离线导入后可使用“测试”按钮更新账号信息，功能不稳定有bug问猫猫": "After offline import, use 'Test' button to update info. Feature unstable (report bugs to Cat).",
    "如果邮箱存在则会覆盖更新，不存在则会新增": "If email exists, it will be updated/overwritten. Otherwise, it will be added.",
    "选择导出的 Token JSON 文件进行导入": "Select exported Token JSON file to import",
    "支持 http 和 socks5 代理，留空则清空代理设置": "Supports http/socks5 proxies. Leave empty to clear.",
    "将为 0 个选中的Token修改代理地址": "Will modify proxy for 0 selected tokens",
    "确认修改": "Confirm Modify",

    # Generate Panel Header & Instructions (Manual Fixes)
    "左侧拖拽/挂载角色卡，中间编写提示词并上传素材，右侧查看任务进度与结果预览。": "Left: Drag/Mount Character Cards. Middle: Write Prompts & Upload Material. Right: Task Progress & Results.",
    "左侧角色卡“挂载”，选择“全局（本模式）”。不会影响单次/同提示。": "Click Character Card 'Mount', select 'Global (This Mode)'. Won't affect Single/Same Prompt.",
    "左侧挂载角色（全局一致），再写每一镜发生的变化；也可以把角色卡拖拽到某一镜文本框，给该镜追加角色。": "Mount characters on left (globally consistent), then describe changes per shot. Or drag Character Card to a shot's text box.",
    "可以先在管理台/生成流程创建角色卡，然后回到这里点击“刷新”。": "Create Character Cards in Admin Console first, then click 'Refresh' here.",
    "拖拽到提示词输入框，或点击“挂载”。收藏会置顶；密集模式更适合角色很多的库。": "Drag to prompt input, or click 'Mount'. Favorites pin to top. Dense mode is better for large libraries.",
    "英文更稳定，可写动作/时长/镜头等": "English recommended. Describe action/duration/camera etc.",
    "提示词 1 （可多行，建议描述镜头/主体/动作/风格）": "Prompt 1 (Multi-line: describe camera/subject/action/style)",
    "单次：只使用 1 个文件；同提示批量：多文件共享同一提示词（每个文件可生成多份）": "Single: Use 1 file. Same Prompt Batch: Multiple files share one prompt (multiple copies per file).",
    "拖拽文件到这里，或点击选择（单次仅 1 个文件）": "Drag files here, or click to select (Single: 1 file only)",
    "视频建议 3~10 秒；批量多选时：同提示多文件共享提示词；多提示每行一句。": "Video: 3-10 sec recommended. Batch: Same Prompt shares across files. Multi-Prompt: one per line.",
    "分镜会一次性创建全部任务并并发发送（不做限流）": "Storyboard creates all tasks at once and sends concurrently (no rate limiting)",
    "把“主提示框”按行拆成分镜：每一行 = 一镜（空行会被忽略）": "Split Main Prompt by line: Each line = One Shot (Empty ignored)",
    "从主提示按行导入": "Import lines from Main Prompt",
    "例如：统一画风、服装、场景、镜头语言、人物特征（建议英文更稳定）": "e.g. Unified style, costume, scene, camera, features (English recommended)",
    "将“全局角色”从某些分镜中排除（这些分镜后续不再受全局自动挂载控制）": "Exclude Global Character from specific shots",
    "角色卡：上传视频创建角色卡，无需提示词": "Character Card: Upload video to create card, no prompt needed",
    "分镜组标题（可选：例如《篮球裁决》）": "Group Title (Optional: e.g. 'Basketball Match')",

    # Common Buttons & Labels
    "批量操作": "Batch Operations",
    "批量启用": "Batch Enable",
    "批量禁用": "Batch Disable",
    "批量修改代理": "Batch Modify Proxy",
    "测试更新": "Test Update",
    "清理禁用": "Clean Disabled",
    "修改代理": "Modify Proxy",
    "导出": "Export",
    "导入": "Import",
    "新增": "Add New",
    "全选": "Select All",
    "邮箱": "Email",
    "状态": "Status",
    "过期时间": "Expires",
    "账户类型": "Account Type",
    "可用次数": "Quota",
    "图片": "Image",
    "视频": "Video",
    "错误": "Error",
    "备注": "Remark",
    "操作": "Action",
    "测试": "Test",
    "编辑": "Edit",
    "禁用": "Disable",
    "启用": "Enable",
    "删除": "Delete",
    "系统配置": "System Config",
    "请求日志": "Request Logs",
    "生成面板": "Generate Panel",
    "安全配置": "Security Config",
    "API 密钥配置": "API Key Config",
    "代理配置": "Proxy Config",
    "错误处理配置": "Error Handling Config",
    "缓存配置": "Cache Config",
    "生成超时配置": "Timeout Config",
    "无水印模式配置": "No-Watermark Config",
    "调试配置": "Debug Config",
    "保存配置": "Save Config",
    "启用代理": "Enable Proxy",
    "启用缓存": "Enable Cache",
    "开启无水印模式": "Enable No-Watermark",
    "启用调试模式": "Enable Debug Mode",
    "下载日志文件": "Download Log",
    "清空日志": "Clear Logs",
    "日志详情": "Log Details",
    "添加 Token": "Add Token",
    "编辑 Token": "Edit Token",
    "导入 Token": "Import Token",
    "导入模式": "Import Mode",
    "功能开关": "Feature Toggles",
    "取消": "Cancel",
    "确认": "Confirm",
    "关闭": "Close",
    "首页": "First",
    "上一页": "Previous",
    "下一页": "Next",
    "末页": "Last",
    "每页显示": "Show",
    "条": "items",
    "共": "Total",
    "页": "pages",
    "暂无数据": "No Data",
    "加载中...": "Loading...",
    "选择文件": "Select File",
    "请选择文件": "Please Select File",
    "导入成功": "Import Successful",
    "导入失败": "Import Failed",
    
    # Missing strings from Screenshots
    "Account类型": "Account Type",
    "TodayImage/总Image": "Today/Total Image",
    "TodayVideo/总Video": "Today/Total Video",
    "TodayError/总Error": "Today/Total Error",
    "Per pageShow": "Show per page",
    "CurrentUse的 API Key (只读)": "Current API Key (Read-only)",
    "Input旧Password": "Enter Old Password",
    "Input新Password": "Enter New Password",
    "Used for客户端调用 API 的Key": "Key used for client API calls",
    "Token 连续Error达到此次数后AutoDisable": "Auto-disable Token after consecutive errors reach this count",
    "Close后，Generate的Image和Video将直接输出原始链接，不会Cache到本地": "If disabled, generated media links are direct and not cached locally",
    "Range: 60-7200 s (1minutes-2hours), Timeout后Back上游APITimeoutError": "Range: 60-7200s. Returns upstream timeout error after timeout",
    "开启NoneWatermark Mode": "Enable No-Watermark Mode",
    "When enabledGenerate的Video将会被发布到sora平台并且提取BackNone水印的Video，在Cache到本地后会AutoDelete发布的Video": "When enabled, videos are published to Sora to extract no-watermark version, then deleted after local caching",
    "密集": "Dense",
    "已Mount": "Mounted",
    "收藏": "Favorite",
    "智能Sort": "Smart Sort",
    "暂无角色卡": "No Character Cards",
    "电影光感": "Cinematic",
    "慢动作": "Slow Mo",
    "广角": "Wide Angle",
    "Batch工具 / 模板": "Batch Tools / Templates",
    "默认Copies": "Default Copies",
    "Import/Export模板": "Import/Export Templates",
    "套用到All": "Apply to All",
    "默认份数": "Default Copies",
    "Global Character (仅多HintMode生效)": "Global Character (Multi-Hint Mode Only)",
    "提示 1": "Prompt 1",
    "份数": "Copies",
    "未选择": "No file selected",
    "清文件": "Clear",
    "Input新 API Key": "Enter New API Key",
    "温馨提示": "Tip",
    "提交": "Submit",
    "重置": "Reset",
    "只看": "Only View",
    "连续": "Continuous",
    "定位": "Locate",
    "过滤": "Filter",
    "按行": "By Line",
    "创建": "Create",
    "拖拽": "Drag",
    "模板": "Template",
    "生效": "Effective",
    "点击左侧": "Click Left",
    "全局": "Global",
    "不会影响": "Won't affect",
    "建议": "Suggestion",
    "输出": "Output",
    "点击": "Click",
    "并重试": "and retry",
    "只保留浏览器主滚动": "Keep only main browser scroll",
    "细微噪点纹理": "Subtle noise texture",
    "增强层次与对比度": "Enhance depth & contrast",
    "不影响主内容交互": "No impact on main content",
    "就绪": "Ready",
    "从灰": "From gray",
    "可点时给一个更明显的脉冲": "Pulse when clickable",
    "尤其重要": "Especially important",
    "两段": "Two steps",
    "更耐看且更久": "More durable & longer",
    "工具栏": "Toolbar",
    "右上角": "Top Right",
    "星是": "Star is",
    "留出右侧空间": "Reserve right space",
    "徽标与星号重叠": "Badge overlaps star",
    "预留更大": "Reserve larger",
    "极端长名": "Extreme long name",
    "缩放下重叠": "Overlap on scale",
    "内部滚动": "Inner scroll",
    "面出现": "Panel appears",
    "双滚动": "Double scroll",
    "计数": "Count",
    "更久一点": "A bit longer",
    "但不喧宾夺主": "But not overwhelming",
    "轻回弹": "Soft bounce",
    "点了没反应": "No reaction on click",
    "久一点": "Longer",
    "的光晕": "halo",
    "不影响可读性": "No impact on readability",
    "变体": "Variant",
    "更明确的": "More explicit",
    "选了图但不相关": "Selected unrelated image",
    "的困惑": "confusion",
    "快切": "Fast Switch",
    "摘要": "Summary",
    "隐藏在高级": "Hidden in advanced",
    "里导致误": "causes mistake",
    "四种": "Four types",
    "统一为": "Unified as",
    "分段": "Segment",
    "减少": "Reduce",
    "的割裂感": "fragmentation",
    "计算并写入": "Calculate & Write",
    "未就绪时仍有选中态": "Selected state when not ready",
    "就绪后": "After ready",
    "统一选中态背景": "Unified selected background",
    "减少割裂感": "Reduce fragmentation",
    "轻量": "Lightweight",
    "面不依赖": "Independent panel",
    "必须有自己的样式": "Must have own style",
    "统一滚动": "Unified scroll",
    "样式": "Style",
    "细滚动": "Fine scroll",
    "更高可辨识度": "Higher visibility",
    "可访问性友好": "Accessibility friendly",
    "编号胶囊": "Number capsule",
    "卡片": "Card",
    "步骤": "Step",
    "桌面优先": "Desktop first",
    "保留双列": "Keep two columns",
    "不做早退降级": "No early degradation",
    "移动端若需适配再单独覆盖": "Mobile adaptation separate",
    "复用": "Reuse",
    "视觉": "Visual",
    "补充更适合长": "Better for long",
    "与编号": "With Number",
    "切换": "Switch",
    "很多时更好用": "Better for many",
    "各自独立": "Independent",
    "最新创建": "Newest",
    "最早创建": "Oldest",
    "拖拽到": "Drag to",
    "或点": "or Click",
    "会置顶": "Will pin to top",
    "更适合": "Better suited",
    "很多的库": "Large library",
    "默认": "Default",
    "可改填自己的": "Can use custom",
    "后端": "Backend",
    "默认本机": "Default Localhost",
    "标准版": "Standard",
    "方图": "Square",
    "横图": "Landscape",
    "竖图": "Portrait",
    "只创建": "Only Create",
    "取第": "Take #",
    "各自": "Each",
    "可给某行附带": "Attach to line",
    "连续剧情更适合": "Better for continuous plot",
    "区会打": "Area check",
    "编号": "No.",
    "便于按顺序找": "Easy to find in order",
    "上传": "Upload",
    "英文更稳定": "English more stable",
    "可写动作": "Write action",
    "镜头等": "Shots etc.",
    "草稿": "Draft",
    "快捷标签": "Quick Tags",
    "高细节": "High Detail",
    "应用到所有": "Apply to All",
    "仅多": "Only Multi",
    "组标题": "Group Title",
    "篮球裁决": "Basket Decision",
    "镜头数": "Shot Count",
    "应用": "Apply",
    "会一次性创建": "Create all at once",
    "并并发发送": "Concurrent send",
    "不做限流": "No rate limit",
    "并发": "Concurrency",
    "按行拆成": "Split by line into",
    "每一行": "Each line",
    "一镜": "One Shot",
    "空行会被忽略": "Empty lines ignored",
    "从主": "From Main",
    "先在左侧": "First on Left",
    "全局一致": "Globally Consistent",
    "再写每一镜发生的变化": "Then write changes per shot",
    "也可以把": "Can also",
    "拖拽到某一镜文本框": "Drag to shot text box",
    "给该镜追加": "Append to shot",
    "从某些": "From some",
    "中排除": "Exclude",
    "这些": "These",
    "后续不再受全局": "No longer affected by global",
    "控制": "control",
    "排除": "Exclude",
    "连续性": "Continuity",
    "统一设定": "Unified Setting",
    "加到每一镜前面": "Add to start of each shot",
    "统一画风": "Unified Style",
    "服装": "Costume",
    "场景": "Scene",
    "镜头语言": "Camera Language",
    "人物特征": "Character Features",
    "建议英文更稳定": "English recommended",
    "上传素材": "Upload Material",
    "多份": "Multiple Copies",
    "到这里": "Here",
    "或点击": "or Click",
    "素材": "Material",
    "切换到": "Switch to",
    "时可多选": "Multi-select when",
    "文本每行一": "One text per line",
    "仅运行中": "Only Running",
    "媒体": "Media",
    "过滤的": "Filtered",
    "打包": "Package",
    "适配": "Adapt",
    "浏览器拦截": "Browser Block",
    "新标签打开": "Open in New Tab",
    "链接": "Link",
    "仅影响": "Only affects",
    "只会重试": "Only retry",
    "不会影响其它": "Won't affect others",
    "建议用更": "Suggest using more",
    "的表达方式": "expressions",
    "开始生成": "Start Generating",
    "新增提示": "Add Prompt",
    "清空输出": "Clear Output",
    "后需要通知所有客户端": "need to notify all clients",
    "会产生非常非常大量的": "will generate a very large amount of",
    "上游获取选中的": "get selected from upstream",
    "铺满主内容宽度": "fill main content width",
    "自定义解析接口": "custom parse API",
    "平台并且提取": "platform and extract",
    "达到此次数后": "after reaching this count",
    "需要单独获取": "need to get separately",
    "将会被发布到": "will be published to",
    "功能不稳定有": "feature unstable may",
    "可能需要较长": "may need longer",
    "存在则会覆盖": "will overwrite if exists",
    "自定义解析": "custom parse",
    "客户端调用": "client call",
    "详细的上游": "detailed upstream",
    "到本地后会": "after caching locally will",
    "标签和开关": "tags and toggles",
    "部署自定义": "deploy custom",
    "第三方解析": "third-party parse",
    "下拉菜单": "dropdown",
    "套餐到期": "plan expires",
    "直接插入": "insert directly",
    "写入完成": "write complete",
    "否则磁盘": "otherwise disk",
    "单层嵌入": "single layer embed",
    "距离过期": "until expiry",
    "时候开启": "when enabled",
    "中间编写": "write in middle",
    "已开启": "enabled",
    "将直接": "will directly",
    "水印的": "watermark",
    "已完成": "completed",
    "不调用": "not call",
    "发布的": "published",
    "和响应": "and response",
    "将写入": "will write to",
    "问猫猫": "Ask Cat",
    "已过期": "expired",
    "到本地": "to local",
    "完整的": "complete",
    "自适应": "adaptive",
    "必须以": "must start with",
    "的访问": "access",
    "完成": "done",
    "导航": "navigation",
    "访问": "access",
    "快速": "quick",
    "如果": "if",
    "右侧": "right side",
    "基本": "basic",
    "左侧": "left side",
    "注意": "note",
    "是否": "whether",
    "原始": "raw",
    "释放": "release",
    "控件": "control",
    "用户": "user",
    "悬浮": "floating",
    "仅限": "only",
    "选项": "option",
    "说明": "description",
    "则会": "will then",
    "高度": "height",
    "等待": "waiting",
    "智能": "smart",
    "完整": "complete",
    "只读": "read-only",
    "开启": "enable",
    "将为": "will be",
    "所有": "all",
    "响应": "response",
    "统计": "statistics",
    "不会": "won't",
    "立即": "immediately",
    "开头": "start with",
    "类型": "type",
    "进行": "proceed",
    "这个": "this",
    "警告": "warning",
    "上游": "upstream",
    "原因": "reason",
    "和新": "and new",
    "有效": "valid",
    "后可": "then can",
    "暂无任务": "No Tasks",
    "暂无日志": "No Logs",
    "运行中": "Running",
    "排队中": "Queued",
    "已完成": "Completed",
    "失败": "Failed",
    "全部": "All",
    "标签": "Tags",
    "分镜": "Storyboard",
    "预览密集": "Preview Dense",
    "单次": "Single",
    "多提示": "Multi-Prompt",
    "同提示": "Same Prompt",
    "请填写提示词或选择一个文件": "Please enter prompt or select a file",
    "拖拽文件到这里": "Drag files here",
    "或点击选择": "or click to select",
    "个文件": "file(s)",
    "个任务": "task(s)",
    "未选择": "Not selected",
    "暂无角色卡": "No Character Cards",
    "分镜（连续提示）": "Storyboard (Continuous Prompt)",
    "选择模型": "Select model",
    "请选择文件": "Please select a file",
    "文件解析失败": "File parsing failed",
    "JSON格式错误：应为数组": "JSON format error: expected array",
    "JSON文件为空": "JSON file is empty",
    "导入": "Import",
    "取消": "Cancel",
    "导入成功": "Import successful",
    "导入失败": "Import failed",
    "批量导出": "Batch Export",
    "批量导入": "Batch Import",
    "批量启用": "Batch Enable",
    "批量禁用": "Batch Disable",
    "批量删除": "Batch Delete",
    "批量修改": "Batch Modify",
    "批量添加": "Batch Add",
    "管理控制台": "Admin Console",
    "Token管理": "Token Management",
    "系统设置": "Settings",
    "请求日志": "Request Logs",
    "生成": "Generate",
    "退出登录": "Logout",
    "记住密码": "Remember Password",
    "登录": "Login",
    "保存": "Save",
    "重置": "Reset",
    "全部": "All",
    "正常": "Normal",
    "异常": "Error",
    "已过期": "Expired",
    "禁用": "Disabled",
    "启用": "Enabled",
    "删除": "Delete",
    "编辑": "Edit",
    "详情": "Details",
    "成功": "Success",
    "失败": "Failed",
    "暂无数据": "No Data",
    "加载中": "Loading...",
    "共": "Total",
    "条": "items",
    "页": "pages",
    "首页": "First",
    "上一页": "Prev",
    "下一页": "Next",
    "末页": "Last",
    "请填写所有必填项": "Please fill all required fields",
    "确认删除": "Confirm Delete",
    "确认": "Confirm",
    "取消": "Cancel",
    "关闭": "Close",
    "提示": "Hint",
    "警告": "Warning",
    "错误": "Error",
    "消息": "Message",
    "无权限": "No Permission",
    "未登录": "Not Login",
    "登录已过期": "Login Expired",
    "请重新登录": "Please login again",
    "未知错误": "Unknown Error",
    "复制": "Copy",
    "下载": "Download",
    "预览": "Preview",
    "上传": "Upload",
    "选择": "Select",
    "搜索": "Search",
    "清空": "Clear",
    "刷新": "Refresh",
    "返回": "Back",
    "更多": "More",
    "设置": "Settings",
    "帮助": "Help",
    "关于": "About",
    "版本": "Version",
    "版权所有": "All Rights Reserved",
    "邮箱": "Email",
    "密码": "Password",
    "验证码": "Verification Code",
    "注册": "Register",
    "找回密码": "Forgot Password",
    "用户名": "Username",
    "昵称": "Nickname",
    "角色": "Role",
    "权限": "Permission",
    "创建时间": "Create Time",
    "更新时间": "Update Time",
    "状态": "Status",
    "备注": "Remark",
    "操作": "Operaion",
    "添加": "Add",
    "修改": "Modify",
    "查看": "View",
    "审核": "Review",
    "通过": "Pass",
    "拒绝": "Reject",
    "提交": "Submit",
    "发送": "Send",
    "接收": "Receive",
    "通知": "Notification",
    "公告": "Announcement",
    "消息": "Message",
    "待办": "Todo",
    "已办": "Done",
    "我的": "My",
    "个人中心": "User Center",
    "修改密码": "Change Password",
    "个人信息": "Profile",
    "安全设置": "Security Settings",
    "日志": "Log",
    "监控": "Monitor",
    "统计": "Statistics",
    "分析": "Analysis",
    "报表": "Report",
    "导出": "Export",
    "导入": "Import",
    "模板": "Template",
    "配置": "Config",
    "参数": "Parameter",
    "接口": "Interface",
    "文档": "Document",
    "说明": "Description",
    "备注": "Note",
    "附件": "Attachment",
    "图片": "Image",
    "视频": "Video",
    "音频": "Audio",
    "文件": "File",
    "文件夹": "Folder",
    "分类": "Category",
    "标签": "Tag",
    "推荐": "Recommend",
    "热门": "Hot",
    "最新": "New",
    "最热": "Hottest",
    "关注": "Follow",
    "粉丝": "Fans",
    "点赞": "Like",
    "评论": "Comment",
    "分享": "Share",
    "收藏": "Favorite",
    "浏览": "View",
    "下载": "Download",
    "上传": "Upload",
    "播放": "Play",
    "暂停": "Pause",
    "停止": "Stop",
    "开始": "Start",
    "结束": "End",
    "完成": "Complete",
    "取消": "Cancel",
    "失败": "Fail",
    "成功": "Success",
    "错误": "Error",
    "警告": "Warning",
    "提示": "Info",
    "确认": "Confirm",
    "选择": "Select",
    "全选": "Select All",
    "反选": "Invert Selection",
    "多选": "Multi Select",
    "单选": "Single Select",
    "搜索": "Search",
    "查询": "Query",
    "筛选": "Filter",
    "排序": "Sort",
    "升序": "Asc",
    "降序": "Desc",
    "分页": "Pagination",
    "上一页": "Prev",
    "下一页": "Next",
    "首页": "First",
    "末页": "Last",
    "跳转": "Go",
    "每页": "Per Page",
    "共": "Total",
    "条": "Items",
    "页": "Pages",
    "刷新": "Refresh",
    "重置": "Reset",
    "加载更多": "Load More",
    "没有更多了": "No More",
    "暂无数据": "No Data",
    "加载中": "Loading...",
    "正在处理": "Processing...",
    "请稍后": "Please wait",
    "稍候": "Wait",
    "保存成功": "Saved successfully",
    "保存失败": "Save failed",
    "操作成功": "Operation successful",
    "操作失败": "Operation failed",
    "上传成功": "Upload successful",
    "上传失败": "Upload failed",
    "下载成功": "Download successful",
    "下载失败": "Download failed",
    "删除成功": "Delete successful",
    "删除失败": "Delete failed",
    "添加成功": "Add successful",
    "添加失败": "Add failed",
    "修改成功": "Modify successful",
    "修改失败": "Modify failed",
    "登录成功": "Login successful",
    "登录失败": "Login failed",
    "注册成功": "Register successful",
    "注册失败": "Register failed",
    "验证码发送成功": "Code sent",
    "验证码发送失败": "Code failed",
    "验证码错误": "Code error",
    "密码错误": "Password error",
    "用户名不存在": "User not found",
    "用户已存在": "User exists",
    "账号已禁用": "Account disabled",
    "账号已锁定": "Account locked",
    "账号已过期": "Account expired",
    "没有权限": "No permission",
    "请求超时": "Request timeout",
    "网络错误": "Network error",
    "服务器错误": "Server error",
    "未知的错误": "Unknown error",
    "链接": "Link",
}

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Sort keys by length descending to prevent shorter matches from breaking longer ones
    sorted_keys = sorted(TRANSLATIONS.keys(), key=len, reverse=True)
    
    for chinese in sorted_keys:
        english = TRANSLATIONS[chinese]
        content = content.replace(chinese, english)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Translated {filepath}")

if __name__ == "__main__":
    translate_file("static/manage.html")
    translate_file("static/login.html")
    translate_file("static/generate.html")
    translate_file("static/js/generate.js")
    print("Done!")
