#!/usr/bin/env python3
"""Translate Chinese strings in HTML files to English"""
import re

TRANSLATIONS = {
    # Page titles
    "管理控制台 - Sora2API": "Admin Console - Sora2API",
    "登录 - Sora2API": "Login - Sora2API",
    "生成 - Sora2API": "Generate - Sora2API",
    
    # Batch operations
    "批量操作": "Batch Operations",
    "批量启用": "Batch Enable",
    "批量禁用": "Batch Disable",
    "批量修改代理": "Batch Modify Proxy",
    "批量测试更新": "Batch Test Update",
    "一键测试更新所有Token": "Test update all tokens at once",
    "一键启用所有禁用的Token": "Enable all disabled tokens",
    "批量禁用选中的Token": "Batch disable selected tokens",
    "批量修改选中Token的代理": "Batch modify proxy for selected tokens",
    "正在批量启用Token...": "Batch enabling tokens...",
    "正在批量禁用Token...": "Batch disabling tokens...",
    "批量启用失败": "Batch enable failed",
    "批量禁用失败": "Batch disable failed",
    "请先选择要启用的Token": "Please select tokens to enable first",
    "请先选择要禁用的Token": "Please select tokens to disable first",
    "请先选择要删除的Token": "Please select tokens to delete first",
    "确定要启用选中的": "Are you sure you want to enable the selected",
    "确定要禁用选中的": "Are you sure you want to disable the selected",
    "个Token吗？": " tokens?",
    "此操作将重置这些Token的错误计数。": "This operation will reset the error count for these tokens.",
    
    # Common UI elements
    "管理控制台": "Admin Console",
    "Token管理": "Token Management",
    "请求日志": "Request Logs",
    "系统设置": "Settings",
    "添加Token": "Add Token",
    "导入Token": "Import Tokens",
    "导出Token": "Export Tokens",
    "刷新": "Refresh",
    "确定": "Confirm",
    "取消": "Cancel",
    "保存": "Save",
    "删除": "Delete",
    "编辑": "Edit",
    "启用": "Enable",
    "禁用": "Disable",
    "状态": "Status",
    "操作": "Actions",
    "邮箱": "Email",
    "代理": "Proxy",
    "备注": "Remark",
    "创建时间": "Created",
    "更新时间": "Updated",
    "过期时间": "Expires",
    "剩余次数": "Remaining",
    "订阅类型": "Subscription",
    "错误次数": "Errors",
    "图片": "Image",
    "视频": "Video",
    "已启用": "Enabled",
    "已禁用": "Disabled",
    "全部": "All",
    "正常": "Normal",
    "异常": "Error",
    "加载中...": "Loading...",
    "暂无数据": "No data",
    "选择文件": "Select file",
    "请选择文件": "Please select a file",
    "导入": "Import",
    "导入中...": "Importing...",
    "导入成功": "Import successful",
    "导入失败": "Import failed",
    "文件解析失败": "File parsing failed",
    "删除失败": "Delete failed",
    "未知错误": "Unknown error",
    
    # Token import
    "导入模式": "Import Mode",
    "使用AT更新账号状态（订阅信息、Sora2次数等）": "Use AT to update account status (subscription, Sora2 count, etc.)",
    "离线导入，不更新账号状态，动态字段显示为-": "Offline import, no status update, dynamic fields show -",
    "自动将ST转换为AT，然后更新账号状态": "Auto convert ST to AT, then update account status",
    "自动将RT转换为AT（并刷新RT），然后更新账号状态": "Auto convert RT to AT (refresh RT), then update account status",
    "导入数据缺少必填字段": "Import data missing required field",
    "缺少必填字段": "Missing required field",
    
    # Request logs
    "任务ID": "Task ID",
    "模型": "Model",
    "Token": "Token",
    "时间": "Time",
    "耗时": "Duration",
    "成功": "Success",
    "失败": "Failed",
    "进行中": "In Progress",
    "等待中": "Pending",
    "已取消": "Cancelled",
    "终止": "Terminate",
    "终止任务": "Terminate Task",
    
    # Settings
    "管理员账户": "Admin Account",
    "用户名": "Username",
    "密码": "Password",
    "当前API密钥": "Current API Key",
    "新API密钥": "New API Key",
    "错误封禁阈值": "Error Ban Threshold",
    "调试模式": "Debug Mode",
    "保存设置": "Save Settings",
    "加载配置失败": "Failed to load config",
    "保存配置失败": "Failed to save config",
    "配置保存成功": "Config saved successfully",
    
    # Delete confirmations
    "第一次确认": "First Confirmation",
    "第二次确认": "Second Confirmation",
    "最后确认": "Final Confirmation",
    "即将删除选中的": "About to delete selected",
    "此操作不可恢复！确定要继续吗？": "This cannot be undone! Are you sure?",
    "你真的确定要删除这": "Are you really sure you want to delete these",
    "删除后无法恢复！": "Deletion cannot be undone!",
    "这是最后一次确认！": "This is the final confirmation!",
    "删除": "Delete",
    "个Token后将无法恢复。": " tokens. This cannot be recovered.",
    "确定要执行删除操作吗？": "Are you sure you want to proceed with deletion?",
    "正在删除选中的Token...": "Deleting selected tokens...",
    
    # Other
    "退出登录": "Logout",
    "登录": "Login",
    "请输入用户名": "Enter username",
    "请输入密码": "Enter password",
    "登录失败": "Login failed",
    "生成面板": "Generate Panel",
    "提示词": "Prompt",
    "生成": "Generate",
    "生成中...": "Generating...",
    "清空": "Clear",
    "复制": "Copy",
    "下载": "Download",
    "一键清理所有禁用的Token": "Clean up all disabled tokens",
    "清理禁用": "Clean Disabled",
    
    # Additional UI strings
    "Token 管理": "Token Management",
    "Token 总数": "Total Tokens",
    "GitHub 仓库": "GitHub Repo",
    "测试更新": "Test Update",
    "选中的Token": "selected tokens",
    "修改代理": "Modify Proxy",
    "代理地址": "Proxy URL",
    "访问Token": "Access Token",
    "会话Token": "Session Token",
    "刷新Token": "Refresh Token",
    "客户端ID": "Client ID",
    "高级选项": "Advanced Options",
    "展开": "Expand",
    "收起": "Collapse",
    "分页": "Pagination",
    "每页": "Per page",
    "条": "items",
    "共": "Total",
    "页": "page(s)",
    "上一页": "Previous",
    "下一页": "Next",
    "首页": "First",
    "末页": "Last",
    "搜索": "Search",
    "筛选": "Filter",
    "排序": "Sort",
    "升序": "Ascending",
    "降序": "Descending",
    "关闭": "Close",
    "确认删除": "Confirm Delete",
    "确认": "Confirm",
    "提交": "Submit",
    "重置": "Reset",
    "返回": "Back",
    "更多": "More",
    "详情": "Details",
    "查看详情": "View Details",
    "编辑Token": "Edit Token",
    "删除Token": "Delete Token",
    "复制成功": "Copied",
    "复制失败": "Copy failed",
    "操作成功": "Operation successful",
    "操作失败": "Operation failed",
    "请稍候": "Please wait",
    "正在加载": "Loading",
    "正在处理": "Processing",
    "请求超时": "Request timeout",
    "网络错误": "Network error",
    "服务器错误": "Server error",
    "无效响应": "Invalid response",
    "格式错误": "Format error",
    "JSON格式错误：应为数组": "JSON format error: expected array",
    "JSON文件为空": "JSON file is empty",
    "选择要导出的Token": "Select tokens to export",
    "导出成功": "Export successful",
    "没有可导出的Token": "No tokens to export",
    "正在测试更新": "Testing update",
    "正在测试Token": "Testing token",
    "测试通过": "Test passed",
    "测试失败": "Test failed",
    "更新成功": "Updated successfully",
    "更新失败": "Update failed",
    "启用成功": "Enabled successfully",
    "禁用成功": "Disabled successfully",
    "无效的Token": "Invalid token",
    "Token已过期": "Token expired",
    "订阅信息": "Subscription info",
    "剩余配额": "Remaining quota",
    "今日已用": "Used today",
    "剩余": "Remaining",
    "无限制": "Unlimited",
    "并发限制": "Concurrency limit",
    "图片并发": "Image concurrency",
    "视频并发": "Video concurrency",
    "不限": "No limit",
    "刷新成功": "Refreshed",
    "刷新失败": "Refresh failed",
    "请重新登录": "Please login again",
    "会话已过期": "Session expired",
    "没有选中任何Token": "No tokens selected",
    "请输入代理地址": "Enter proxy URL",
    "代理格式错误": "Invalid proxy format",
    "设置代理成功": "Proxy set successfully",
    "设置代理失败": "Failed to set proxy",
    "清空代理": "Clear proxy",
    "确定要清空所有选中Token的代理吗？": "Clear proxy for all selected tokens?",
    "正在设置代理": "Setting proxy",
    "添加成功": "Added successfully",
    "添加失败": "Add failed",
    "保存成功": "Saved successfully",
    "保存失败": "Save failed",
    "请填写必填项": "Please fill in required fields",
    "格式不正确": "Invalid format",
    "长度超出限制": "Length exceeds limit",
    "已存在": "Already exists",
    "不存在": "Does not exist",
    "无权限": "No permission",
    "请先登录": "Please login first",
    "正在退出": "Logging out",
    "退出成功": "Logged out",
    "输入提示词": "Enter prompt",
    "选择模型": "Select model",
    "图片生成": "Image Generation",
    "视频生成": "Video Generation",
    "提示词增强": "Prompt Enhancement",
    "参考图片": "Reference Image",
    "上传图片": "Upload Image",
    "点击上传": "Click to upload",
    "或拖拽文件到此处": "or drag file here",
    "支持的格式": "Supported formats",
    "最大文件大小": "Max file size",
    "生成结果": "Result",
    "生成耗时": "Generation time",
    "秒": "s",
    "下载视频": "Download Video",
    "下载图片": "Download Image",
    "重新生成": "Regenerate",
    "历史记录": "History",
    "清空历史": "Clear History",
    "确定清空历史记录？": "Clear all history?",
    "无历史记录": "No history",
    "生成配置": "Generation Config",
    "风格": "Style",
    "无": "None",
    "时长": "Duration",
    "分辨率": "Resolution",
    "横屏": "Landscape",
    "竖屏": "Portrait",
    "比例": "Aspect Ratio",
    "请输入": "Please enter",
    "正在上传": "Uploading",
    "上传成功": "Upload successful",
    "上传失败": "Upload failed",
    "文件过大": "File too large",
    "不支持的文件类型": "Unsupported file type",
    "进度": "Progress",
    "所有Token": "All Tokens",
    "可用Token": "Available Tokens",
    "不可用Token": "Unavailable Tokens",
    "错误Token": "Error Tokens",
    "无可用Token": "No available tokens",
    "正在初始化": "Initializing",
    "系统配置": "System Config",
}

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for chinese, english in TRANSLATIONS.items():
        content = content.replace(chinese, english)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Translated {filepath}")

if __name__ == "__main__":
    translate_file("static/manage.html")
    translate_file("static/login.html")
    translate_file("static/generate.html")
    print("Done!")
